---

# Обязательное задание 4 - анализ рынка видеоигр

В качестве ответа пришлите файл .ipynb в формате задание - решение - комментарий/вывод (если необходимо)

## Описание данных

Датасет содержит информацию о видеоиграх с 1980 по 2016 год.

| Столбец | Описание |
|---|---|
| `Name` | Название игры |
| `Platform` | Платформа |
| `Year_of_Release` | Год выпуска |
| `Genre` | Жанр |
| `NA_sales` | Продажи в Северной Америке, млн копий |
| `EU_sales` | Продажи в Европе, млн копий |
| `JP_sales` | Продажи в Японии, млн копий |
| `Other_sales` | Продажи в других регионах, млн копий |
| `Critic_Score` | Оценка критиков (0–100) |
| `User_Score` | Оценка пользователей (0–10) |
| `Rating` | Возрастной рейтинг ESRB |

---

## Задача 1. Загрузка данных

Загрузите файл, выведите первые 10 строк, типы данных и количество пропусков в каждом столбце.

###Решение

In [618]:
# Загрузим файл и выведем первые 10 строк
import pandas as pd
import numpy as np

df = pd.read_csv('games.csv')
df.head(10)

,Name,Platform,Year_of_Release,Genre,NA_sales,EU_sales,JP_sales,Other_sales,Critic_Score,User_Score,Rating
0,Wii Sports,Wii,2006.0,Sports,41.36,28.96,3.77,8.45,76.0,8,E
1,Super Mario Bros.,NES,1985.0,Platform,29.08,3.58,6.81,0.77,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,15.68,12.76,3.79,3.29,82.0,8.3,E
3,Wii Sports Resort,Wii,2009.0,Sports,15.61,10.93,3.28,2.95,80.0,8,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,11.27,8.89,10.22,1.00,NaN,NaN,NaN
5,Tetris,GB,1989.0,Puzzle,23.20,2.26,4.22,0.58,NaN,NaN,NaN
6,New Super Mario Bros.,DS,2006.0,Platform,11.28,9.14,6.50,2.88,89.0,8.5,E
7,Wii Play,Wii,2006.0,Misc,13.96,9.18,2.93,2.84,58.0,6.6,E
8,New Super Mario Bros. Wii,Wii,2009.0,Platform,14.44,6.94,4.70,2.24,87.0,8.4,E
9,Duck Hunt,NES,1984.0,Shooter,26.93,0.63,0.28,0.47,NaN,NaN,NaN

In [619]:
# Выведем типы данных
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16715 entries, 0 to 16714
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             16713 non-null  object
 1   Platform         16715 non-null  object
 2   Year_of_Release  16446 non-null  float64
 3   Genre            16713 non-null  object
 4   NA_sales         16715 non-null  float64
 5   EU_sales         16715 non-null  float64
 6   JP_sales         16715 non-null  float64
 7   Other_sales      16715 non-null  float64
 8   Critic_Score     8137 non-null   float64
 9   User_Score       10014 non-null  object
 10  Rating           9949 non-null   object
dtypes: float64(6), object(5)
memory usage: 1.4+ MB

In [620]:
# Выведем количество пропусков в каждом столбце
df.isna().sum()

Name                  2
Platform              0
Year_of_Release     269
Genre                 2
NA_sales              0
EU_sales              0
JP_sales              0
Other_sales           0
Critic_Score       8578
User_Score         6701
Rating             6766
dtype: int64

---

## Задача 2. Очистка данных

- Приведите названия столбцов к нижнему регистру.
- В `user_score` замените  `'tbd'` на `NaN` и объясните, что оно означает.
- Приведите `user_score` к числовому типу, `year_of_release` — к целочисленному. (подсказка: для замены поможет метод `.replace`, для создания NaN - библиотека `import numpy as np` и `np.nan`, для преобразования к числовому типу используйте типы данных с поддержкой NaN - Int64, Float32 и тд)

###Решение

In [621]:
# Приведем названия столбцов к нижнему регистру

df.columns = (col.lower() for col in df.columns)

In [622]:
# Проверим, что названия столбцов стали в нижнем регистре. Для этого выведем первые три строки

df.head(3)

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
0,Wii Sports,Wii,2006.0,Sports,41.36,28.96,3.77,8.45,76.0,8,E
1,Super Mario Bros.,NES,1985.0,Platform,29.08,3.58,6.81,0.77,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,15.68,12.76,3.79,3.29,82.0,8.3,E

In [623]:
# В user_score заменим 'tbd' на NaN

df['user_score'] = df['user_score'].replace('tbd', np.nan)

In [624]:
# Проверим, что 'tbd' заменилось на NaN. Для этого выведем все уникальные значения столбца user_score

df['user_score'].unique()

array(['8', nan, '8.3', '8.5', '6.6', '8.4', '8.6', '7.7', '6.3', '7.4',
       '8.2', '9', '7.9', '8.1', '8.7', '7.1', '3.4', '5.3', '4.8', '3.2',
       '8.9', '6.4', '7.8', '7.5', '2.6', '7.2', '9.2', '7', '7.3', '4.3',
       '7.6', '5.7', '5', '9.1', '6.5', '8.8', '6.9', '9.4', '6.8', '6.1',
       '6.7', '5.4', '4', '4.9', '4.5', '9.3', '6.2', '4.2', '6', '3.7',
       '4.1', '5.8', '5.6', '5.5', '4.4', '4.6', '5.9', '3.9', '3.1',
       '2.9', '5.2', '3.3', '4.7', '5.1', '3.5', '2.5', '1.9', '3', '2.7',
       '2.2', '2', '9.5', '2.1', '3.6', '2.8', '1.8', '3.8', '0', '1.6',
       '9.6', '2.4', '1.7', '1.1', '0.3', '1.5', '0.7', '1.2', '2.3',
       '0.5', '1.3', '0.2', '0.6', '1.4', '0.9', '1', '9.7'], dtype=object)

'tbd' расшифровывается как: To Be Determined или To Be Decided - в переводе 'будет определено позже' или 'будет решено позже'. В датасетах это просто текстовая заглушка и ее лучше заменить на NaN для дальнейшей работы с пропусками

In [625]:
# Приведем user_score к числовому типу

df['user_score'] = df['user_score'].astype('Float64')

# Приведем year_of_release к целочисленному типу

df['year_of_release'] = df['year_of_release'].astype('Int64')

In [626]:
# Проверим, что типы данных в столбцах поменялись. Для этого выведем информацию о типах данных во всей таблице

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16715 entries, 0 to 16714
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             16713 non-null  object
 1   platform         16715 non-null  object
 2   year_of_release  16446 non-null  Int64
 3   genre            16713 non-null  object
 4   na_sales         16715 non-null  float64
 5   eu_sales         16715 non-null  float64
 6   jp_sales         16715 non-null  float64
 7   other_sales      16715 non-null  float64
 8   critic_score     8137 non-null   float64
 9   user_score       7590 non-null   Float64
 10  rating           9949 non-null   object
dtypes: Float64(1), Int64(1), float64(5), object(4)
memory usage: 1.4+ MB

---

## Задача 3. Суммарные продажи

- Добавьте столбец `total_sales` — сумму продаж по всем регионам.
- Выведите топ-10 игр по мировым продажам.
- Найдите игру с наибольшими продажами отдельно в NA, EU и JP.

###Решение

In [627]:
# Добавим столбец total_sales
df['total_sales'] = df['na_sales'] + df['eu_sales'] + df['jp_sales'] + df['other_sales']

In [628]:
# Выведем топ-10 игр по мировым продажам
df.sort_values('total_sales', ascending=False).head(10)

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating,total_sales
0,Wii Sports,Wii,2006,Sports,41.36,28.96,3.77,8.45,76.0,8.0,E,82.54
1,Super Mario Bros.,NES,1985,Platform,29.08,3.58,6.81,0.77,NaN,<NA>,NaN,40.24
2,Mario Kart Wii,Wii,2008,Racing,15.68,12.76,3.79,3.29,82.0,8.3,E,35.52
3,Wii Sports Resort,Wii,2009,Sports,15.61,10.93,3.28,2.95,80.0,8.0,E,32.77
4,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,11.27,8.89,10.22,1.00,NaN,<NA>,NaN,31.38
5,Tetris,GB,1989,Puzzle,23.20,2.26,4.22,0.58,NaN,<NA>,NaN,30.26
6,New Super Mario Bros.,DS,2006,Platform,11.28,9.14,6.50,2.88,89.0,8.5,E,29.80
7,Wii Play,Wii,2006,Misc,13.96,9.18,2.93,2.84,58.0,6.6,E,28.91
8,New Super Mario Bros. Wii,Wii,2009,Platform,14.44,6.94,4.70,2.24,87.0,8.4,E,28.32
9,Duck Hunt,NES,1984,Shooter,26.93,0.63,0.28,0.47,NaN,<NA>,NaN,28.31

In [629]:
# Найдем игру с наибольшими продажами в NA
df.loc[df['na_sales'].idxmax()]

name               Wii Sports
platform                  Wii
year_of_release          2006
genre                  Sports
na_sales                41.36
eu_sales                28.96
jp_sales                 3.77
other_sales              8.45
critic_score             76.0
user_score                8.0
rating                      E
total_sales             82.54
Name: 0, dtype: object

In [630]:
# Найдем игру с наибольшими продажами в EU
df.loc[df['eu_sales'].idxmax()]

name               Wii Sports
platform                  Wii
year_of_release          2006
genre                  Sports
na_sales                41.36
eu_sales                28.96
jp_sales                 3.77
other_sales              8.45
critic_score             76.0
user_score                8.0
rating                      E
total_sales             82.54
Name: 0, dtype: object

In [631]:
# Найдем игру с наибольшими продажами в JP
df.loc[df['jp_sales'].idxmax()]

name               Pokemon Red/Pokemon Blue
platform                                 GB
year_of_release                        1996
genre                          Role-Playing
na_sales                              11.27
eu_sales                               8.89
jp_sales                              10.22
other_sales                             1.0
critic_score                            NaN
user_score                             <NA>
rating                                  NaN
total_sales                           31.38
Name: 4, dtype: object

---

## Задача 4. Выпуск игр по годам

- Подсчитайте количество игр по годам и выведите таблицу.
- Определите год с наибольшим количеством релизов.

###Решение

In [632]:
# Подсчитаем количество игр по годам и выведем таблицу

df_number_of_games = df.groupby('year_of_release')['name'].count().reset_index()

# Поменяем название столбца на более подходящее
df_number_of_games = df_number_of_games.rename(columns={'name': 'number_of_games'})
df_number_of_games

    year_of_release  number_of_games
0              1980                9
1              1981               46
2              1982               36
3              1983               17
4              1984               14
5              1985               14
6              1986               21
7              1987               16
8              1988               15
9              1989               17
10             1990               16
11             1991               41
12             1992               43
13             1993               60
14             1994              121
15             1995              219
16             1996              263
17             1997              289
18             1998              379
19             1999              338
20             2000              350
21             2001              482
22             2002              829
23             2003              775
24             2004              762
25             2005              939
26             2006             1006
27             2007             1197
28             2008             1427
29             2009             1426
30             2010             1255
31             2011             1136
32             2012              653
33             2013              544
34             2014              581
35             2015              606
36             2016              502

In [633]:
# Определим год с наибольшим количеством релизов
df_number_of_games.loc[df_number_of_games['number_of_games'].idxmax()]

year_of_release    2008
number_of_games    1427
Name: 28, dtype: Int64

---

## Задача 5. Анализ платформ

Для отфильтрованного датасета выведите таблицу: платформа — суммарные продажи — количество игр — медианные продажи на игру. Определите топ-5 платформ.

###Решение

In [634]:
# Выведем таблицу: платформа — суммарные продажи — количество игр — медианные продажи на игру
df_platform = df.groupby('platform', as_index=False).agg(
    sum_sales=('total_sales', 'sum'),
    number_of_games=('name', 'count'),
    median_sales=('total_sales', 'median'))
df_platform

   platform  sum_sales  number_of_games  median_sales
0      2600      96.98              133         0.460
1       3DO       0.10                3         0.020
2       3DS     259.00              520         0.120
3        DC      15.95               52         0.135
4        DS     806.12             2151         0.110
5        GB     255.46               98         1.165
6       GBA     317.85              822         0.160
7        GC     198.93              556         0.150
8       GEN      30.77               27         0.150
9        GG       0.04                1         0.040
10      N64     218.68              319         0.270
11      NES     251.05               98         1.375
12       NG       1.44               12         0.100
13       PC     259.52              974         0.050
14     PCFX       0.03                1         0.030
15       PS     730.86             1197         0.260
16      PS2    1255.77             2161         0.230
17      PS3     939.65             1331         0.270
18      PS4     314.14              392         0.200
19      PSP     294.05             1209         0.090
20      PSV      54.07              430         0.055
21      SAT      33.59              173         0.120
22      SCD       1.86                6         0.065
23     SNES     200.04              239         0.320
24     TG16       0.16                2         0.080
25       WS       1.42                6         0.215
26      Wii     907.51             1320         0.190
27     WiiU      82.19              147         0.220
28     X360     971.42             1262         0.280
29       XB     257.74              824         0.150
30     XOne     159.32              247         0.220

Т.к в задании не сказано по каким параметрам определить топ-5 платформ, то определим топ-5 платформ по каждому столбцу

In [635]:
# Определим топ-5 платформ по суммарным продажам
df_platform.sort_values('sum_sales', ascending=False).head(5)

   platform  sum_sales  number_of_games  median_sales
16      PS2    1255.77             2161          0.23
28     X360     971.42             1262          0.28
17      PS3     939.65             1331          0.27
26      Wii     907.51             1320          0.19
4        DS     806.12             2151          0.11

In [636]:
# Определим топ-5 платформ по количеству игр
df_platform.sort_values('number_of_games', ascending=False).head(5)

   platform  sum_sales  number_of_games  median_sales
16      PS2    1255.77             2161          0.23
4        DS     806.12             2151          0.11
17      PS3     939.65             1331          0.27
26      Wii     907.51             1320          0.19
28     X360     971.42             1262          0.28

In [637]:
# Определим топ-5 платформ по медианным продажам на игру
df_platform.sort_values('median_sales', ascending=False).head(5)

   platform  sum_sales  number_of_games  median_sales
11      NES     251.05               98         1.375
5        GB     255.46               98         1.165
0      2600      96.98              133         0.460
23     SNES     200.04              239         0.320
28     X360     971.42             1262         0.280

---

## Задача 6. Анализ жанров

Для каждого жанра рассчитайте суммарные и медианные продажи, количество игр. Выведите таблицу по убыванию суммарных продаж. Определите самый прибыльный жанр и жанр с наибольшими медианными продажами.

###Решение

In [638]:
# Для каждого жарна рассчитаем суммарные и медианные продажи, количество игр. Выведем таблицу по убыванию суммарных продаж
df_genre = df.groupby('genre', as_index=False).agg(
    sum_sales=('total_sales', 'sum'),
    median_sales=('total_sales', 'median'),
    number_of_games=('name', 'count')
)
df_genre.sort_values('sum_sales', ascending=False)

           genre  sum_sales  median_sales  number_of_games
0         Action    1744.17          0.19             3369
10        Sports    1331.27          0.22             2348
8        Shooter    1052.45          0.24             1323
7   Role-Playing     934.56          0.18             1498
4       Platform     827.77          0.27              888
3           Misc     802.51          0.16             1750
6         Racing     728.67          0.19             1249
2       Fighting     447.53          0.21              849
9     Simulation     389.97          0.15              873
5         Puzzle     242.57          0.11              580
1      Adventure     237.59          0.05             1303
11      Strategy     174.23          0.10              683

In [639]:
# Определим самый прибыльный жанр
top_genre = df_genre.loc[df_genre['sum_sales'].idxmax(), 'genre']
print('Самый прибыльный жанр:', top_genre)

Самый прибыльный жанр: Action

In [640]:
# Определим жанр с наибольшими медианными продажами
top_genre = df_genre.loc[df_genre['median_sales'].idxmax(), 'genre']
print('Жанр с наибольшими медианными продажами:', top_genre)

Жанр с наибольшими медианными продажами: Platform

---

## Задача 7. Региональные предпочтения: жанры и рейтинг

- Для каждого региона выведите топ-5 жанров по продажам.
- Рассчитайте суммарные продажи по рейтингу ESRB в каждом регионе. Какой рейтинг лидирует?

###Решение

In [641]:
# Для каждого региона выведем топ-5 жанров по продажам

# Создадим таблицу в которой будет не 4 столбца с разными регионами, а один столбец с четырьмя регионами
cols = ['na_sales', 'eu_sales', 'jp_sales', 'other_sales']
df_melted = df.melt(
    id_vars=['genre'],
    value_vars=cols,
    var_name='region',
    value_name='sales'
)

# Суммируем продажи по регионам и рейтингу
df_melted_sum = df_melted.groupby(['region', 'genre'], as_index=False)['sales'].sum()

# Заменим названия регионов на более понятные
regions = {'eu_sales': 'EU', 'jp_sales': 'Japan', 'na_sales': 'North America', 'other_sales': 'Other countries'}
df_melted_sum['region'] = df_melted_sum['region'].replace(regions)

# Выведем топ-5 жанров по продажам в регионах
df_melted_sum.sort_values(['region', 'sales'], ascending=[True, False]).groupby('region', group_keys=False).head()

             region         genre   sales
0                EU        Action  519.13
10               EU        Sports  376.79
8                EU       Shooter  317.34
6                EU        Racing  236.51
3                EU          Misc  212.74
19            Japan  Role-Playing  355.41
12            Japan        Action  161.43
22            Japan        Sports  135.54
16            Japan      Platform  130.83
15            Japan          Misc  108.11
24    North America        Action  879.01
34    North America        Sports  684.43
32    North America       Shooter  592.24
28    North America      Platform  445.50
27    North America          Misc  407.27
36  Other countries        Action  184.60
46  Other countries        Sports  134.51
44  Other countries       Shooter  104.11
42  Other countries        Racing   76.10
39  Other countries          Misc   74.39

Рассчитаем суммарные продажи по рейтингу ESRB в каждом регионе. Выведем таблицу с лидерами по рейтингу в каждом регионе

In [642]:
# Проверим есть ли пропуски в столбце rating
df['rating'].isna().sum()

np.int64(6766)

In [643]:
# Заменим NaN на Unknown
df['rating'] = df['rating'].fillna('Unknown')

# Создадим таблицу в которой будет не 4 столбца с разными регионами, а один столбец с четырьмя регионами
cols = ['na_sales', 'eu_sales', 'jp_sales', 'other_sales']
df_melted = df.melt(
    id_vars=['rating'],
    value_vars=cols,
    var_name='region',
    value_name='sales'
)

# Суммируем продажи по регионам и рейтингу
df_melted_sum = df_melted.groupby(['region', 'rating'], as_index=False)['sales'].sum()

# Найдем индексы строк с максимальными продажами
leaders = df_melted_sum.groupby('region')['sales'].idxmax()

# Получим таблицу с лидерами по рейтингу
df_leaders = df_melted_sum.loc[leaders].sort_values('region')

# Заменим названия регионов на более понятные и выведем конечную таблицу
regions = {'eu_sales': 'EU', 'jp_sales': 'Japan', 'na_sales': 'North America', 'other_sales': 'Other countries'}
df_leaders['region'] = df_leaders['region'].replace(regions)
df_leaders

             region   rating    sales
1                EU        E   710.25
17            Japan  Unknown   841.96
19    North America        E  1292.99
28  Other countries        E   234.17

####Вывод
Исходя из таблицы видим, что наибольшие суммарные продажи игр во всех регионах с рейтингом E, кроме Японии. Там наибольшие суммарные продажи у игр без рейтинга